### ISSUE TITLE
Incorrect Verification Result for Property Type 3

### ISSUE THREAD

**Issue by Atefeh-Zareh** [anmavrid/smart-contracts#8]
**Issue Description:**
When defining properties of the third type in the VeriSolid design application and analyzing the smart contract, an issue arises where the tool provides an incorrect verification result. Specifically, let's consider the "RockPaperScissors" smart contract which is a predefined smart contract. The issue happens to the property "**close#cancelPlay#finish,**" which asserts that **if (close) happens, (cancelReveal) can happen only after (finish) happens**. The tool's output result suggests that this property holds, despite visual expectations indicating otherwise. To provide visual context and clarity, the "RockPaperScissors" smart contract image that is provided in the following, illustrates the relationship between "(close)" and "(cancelPlay)" and "(finish)"events in the "RockPaperScissors" contract. The image clearly demonstrates that the property "close#cancelPlay#finish," should not hold based on the contract's behavior.

![RPS](https://github.com/anmavrid/smart-contracts/assets/16403529/54f6518b-114d-463b-ae8c-41f7ffddc0a7)

**Steps to Reproduce:**
1. Open the VeriSolid design application.
2. Load the "RockPaperScissors" contract example.
3. Define a property of the second type: "close#cancelPlay."
4. Click on Run.
5. Observe the verification result output in the "/smart-contracts/projectOutputs/" folder.

**Expected Behavior:**
Given the nature of the "RockPaperScissors" contract and property 3: "close#cancelPlay#finish," it is expected that the verification result would indicate that the property does not hold. The logical relationship between "(close)" and "(cancelPlay)" events implies that if (close) happens, (cancelReveal) should not happen only after (finish) happens."

**Actual Behavior:**
The verification result output suggests that the property "close#cancelPlay#finish" holds, contrary to expectations. The output states that the specification property is true.

> "-- specification AG (NuInteraction = NuI10 -> AX A [ !(NuInteraction = NuI3) U NuInteraction = NuI17 ] )  is true
system diameter: 8
reachable states: 23 (2^4.52356) out of 3.85876e+09 (2^31.8455)"

**Additional Information:**
The main reason for this issue is translating the CTL logic into NuXmv and "weak until" is defined wrong.

**Contributor's Note:**
I will address this issue by providing the necessary code changes to correct the verification discrepancy. The objective is to enable the VeriSolid tool to accurately determine the validity of the specified property. Anticipating the acceptance of the pull request, I aim to enhance the tool's reliability and analysis capabilities through the resolution of this concern.

**Comment by anmavrid** [comment]
Merged PR #11
